### ISSUE TITLE
Cannot run lein install on a new reagent project

### ISSUE THREAD

**Issue by tmtwd** [reagent-project/reagent-template#123]
running `lein install` on new reagent project generated from the template does not work

(project generated with `lein new reagent middleware-error-reagent`)

middleware-error-reagent$ lein install
Retrieving reagent-forms/reagent-forms/0.5.25/reagent-forms-0.5.25.pom from clojars
Retrieving reagent-forms/reagent-forms/0.5.25/reagent-forms-0.5.25.jar from clojars

minifying assets...

minifying: /Users/tmtwd/middleware-error-reagent/resources/public/css/site.min.css
assets: site.css
original size: 448
compressed size: 352
gzipped size: 248
Compiling middleware-error-reagent.server
java.io.FileNotFoundException: Could not locate middleware_error_reagent/middleware__init.class or middleware_error_reagent/middleware.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name., compiling:(handler.clj:1:1)
Exception in thread "main" java.io.FileNotFoundException: Could not locate middleware_error_reagent/middleware__init.class or middleware_error_reagent/middleware.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name., compiling:(handler.clj:1:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
	at clojure.lang.Compiler.compile1(Compiler.java:7474)
	at clojure.lang.Compiler.compile1(Compiler.java:7464)
	at clojure.lang.Compiler.compile(Compiler.java:7541)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)

I've found I could fix the issue by removing this require statement from `handler.clj`

`[middleware-error-reagent.middleware :refer [wrap-middleware]]`

**Comment by yogthos** [comment]
You're not supposed to use `lein install` to package the application. It should be built using `lein uberjar` instead.

**Comment by tmtwd** [comment]
ok, sounds good
