### ISSUE TITLE
Error on (reload-config) on a new project +devcards

### ISSUE THREAD

**Issue by vibl** [reagent-project/reagent-template#96]
Error on `(reload-config)` on a new project `+devcards`.

These commands execute without any error message:
```
lein new reagent new-reagent+devcards +devcards
cd new-reagent+devcards
rlwrap lein figwheel devcards
```
Then:
```
(reload-config)
Figwheel: Stopped watching build - devcards
Figwheel: Reloading build config information
Figwheel: Cleaning build - devcards
clojure.lang.ExceptionInfo: Missing component autobuild-devcards from system {:reason :com.stuartsierra.component/missing-component, :system-key "autobuild-devcards", :system #<SystemMap>}
        at clojure.core$ex_info.invoke(core.clj:4593)
        at com.stuartsierra.component$get_component.invoke(component.cljc:61)
        at com.stuartsierra.component$update_system$fn__14987.invoke(component.cljc:137)
        at clojure.lang.ArraySeq.reduce(ArraySeq.java:109)
        at clojure.core$reduce.invoke(core.clj:6518)
        at com.stuartsierra.component$update_system.doInvoke(component.cljc:135)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at com.stuartsierra.component$start_system.invoke(component.cljc:163)
        at figwheel_sidecar.system$stop_and_start_watchers.invoke(system.clj:256)
        at figwheel_sidecar.system$reload_config.invoke(system.clj:361)
        at figwheel_sidecar.system$build_figwheel_special_fns$fn__16606.invoke(system.clj:438)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:632)
        at figwheel_sidecar.system$system_setter$fn__16601.doInvoke(system.clj:425)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at figwheel_sidecar.system$make_special_fn$self__16597.invoke(system.clj:416)
        at cljs.repl$repl_STAR_$read_eval_print__4856.invoke(repl.cljc:855)
        at cljs.repl$repl_STAR_$fn__4862$fn__4871.invoke(repl.cljc:896)
        at cljs.repl$repl_STAR_$fn__4862.invoke(repl.cljc:895)
        at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1149)
        at cljs.repl$repl_STAR_.invoke(repl.cljc:859)
        at figwheel_sidecar.repl$eval15313$fn__15314.invoke(repl.clj:148)
        at clojure.lang.MultiFn.invoke(MultiFn.java:238)
        at figwheel_sidecar.repl$repl.invoke(repl.clj:165)
        at figwheel_sidecar.system$start_figwheel_repl.invoke(system.clj:471)
        at figwheel_sidecar.system$figwheel_cljs_repl_STAR_.invoke(system.clj:515)
        at figwheel_sidecar.system$build_switching_cljs_repl_STAR_.invoke(system.clj:521)
        at figwheel_sidecar.system$cljs_repl_STAR_.invoke(system.clj:541)
        at figwheel_sidecar.system$cljs_repl.invoke(system.clj:565)
        at figwheel_sidecar.system$cljs_repl.invoke(system.clj:561)
        at figwheel_sidecar.repl_api$start_figwheel_from_lein.invoke(repl_api.clj:129)
        at user$eval16677.invoke(form-init1729566623454387671.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6782)
        at clojure.lang.Compiler.eval(Compiler.java:6772)
        at clojure.lang.Compiler.load(Compiler.java:7227)
        at clojure.lang.Compiler.loadFile(Compiler.java:7165)
        at clojure.main$load_script.invoke(main.clj:275)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invoke(main.clj:308)
        at clojure.main$null_opt.invoke(main.clj:343)
        at clojure.main$main.doInvoke(main.clj:421)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
```

**Comment by zjhmale** [comment]
i will take a look at this issue.

**Comment by yogthos** [comment]
great!
